### ISSUE TITLE
Some (probably low hanging fruits) improvements

### ISSUE THREAD

**Issue by FelixBrendel** [fsparv/LeelaWatcher#11]
These are just some features that would make watching a lot more enjoyable.
(In addition to board coordinates and last played indicators from #2)

- Higher resolution go board image
- Textures for the go stones
- Have a title for the window
- Display the seconds per game (the output of autogtp) in the Title
- Option to play a small sound when a game finished (when I am
  working and have it in the background I will feel reminded that I am
  helping to train an amazing AI)
- Option to not save sgfs

I will look through your code and try to make a PR, but I also wanted to write down the list first, so others can help as well. 

What do you think?

**Comment by fsparv** [comment]
**Board Image**: easy, but need to find one that is free to use and compatible with Apache 2 license. Suggestions welcome

**Stone Images**: somewhat harder, but not terrible I think. Do have to mess with the painting code since I think it's just solid fill right now.

**Window title:** Yeah that should be easy.

**Seconds per game**: would be nice, but parsing that output will be quite brittle. Really the whole thing is quite brittle. I would want to coordinate the author of Leela Zero before baking in any further dependence on his non-standardized output. As it stands, projects like this one are a bit of a pain for him, because someday he might change the wording/spacing/etc in the messages  that I'm parsing and then he'll get bug reports that he broke the watcher program that he never intended to support. So the tighter my parsing is the more brittle it is. I'd love to hear his thoughts on how to coordinate, but I suspect that would lead to my needing to do a lot of implementation to handle GTP or something like that, So while this would be good, it's not low hanging.

**Sound when finished**: Yeah that would be nice, have to find an appropriately licensed media file, suggestions welcome :)

**Not save SGF**: yeah I have already had this in the back of my mind as a potential command line switch.

**Comment by fsparv** [comment]
Better board image, not saving, window title, and last move marker are now available in 1.1.0. Closing this, other harder options listed above can be revived in independent tickets, one per feature. Thx for the suggestions and contribution
