### ISSUE TITLE
Unable to run

### ISSUE THREAD

**Issue by ddragon292** [fsparv/LeelaWatcher#17]
I cant find the .jar file and dont know what your talking about when you ask to change the binary file name to the one supplied. when i try to enter in the supplied command into my command line after changing to the proper directory it only tells me that the associated jar file cannot be run.

TL/DR: I need a "for dummies" explanation of how to get this to run properly on windows.

also, as a side note; a more user friendly version overall of this program may do wonders for getting people to contribute to the Leela Zero project. Perhaps a version that runs as a simple screen saver.

**Comment by fsparv** [comment]
The jar file is released here: https://github.com/fsparv/LeelaWatcher/releases 

This is a free open source software project, not officially affiliated with LeelaZero in any way, though I am flattered to have been given a mention on their front page. This is not commercial software. I wrote this in my spare time because I thought it would be fun and some folks might enjoy it. 

My time with respect to this is donated and demanding things or berating stuff as it is won't get anywhere. (Paying me however would work, I am a consultant and I do write software for money)

If you are willing to put in the effort of providing a clear, fully descriptive example of what you tried (exact commands, etc), what you saw (screen shots, program output, etc) and what you expected to see, then if I am not slammed with work that I get paid for, I will often find the time to help you understand what went wrong, and fix anything I deem to be worthy of fixing. On the other hand if you continue to cite your own ignorance and unwillingness to learn as reasons for me to implement things, I'll very likely ignore you.

Feature suggestions are certainly welcome, but like all open source projects if you really want a feature, the best way is to pitch in and donate some of your time by contributing a patch for it. (Careful attention to normal development and patch contribution processes will make that go smoother of course).

Incidentally there is a patch in progress from a contributor for some UI enhancements, though a few details need to be attended to before it can be included. AFAIK screen savers are a very platform specific feature usually requiring native code, and a lot more effort. This project is pure java, so as nice as such a thing would be, I don't see that happening any time soon.

**Comment by fsparv** [comment]
Some useful links:

https://opensource.guide/how-to-contribute/

https://testlio.com/blog/the-ideal-bug-report/

**Comment by ddragon292** [comment]
whoa whoa whoa, I don't exactly understand where you're seeing anything negative directed toward anybody with the exception of a little self defacing humor directed at myself. I didn't know the main java file was missing from the page linked by the Leela Zero project page (never used GITHUB before and didnt know how to navigate to the releases tab, the main leela page just links it in the description), the Jar file you supplied was all i needed. The latter was simply a suggestion to further the project and was in no way meant to bruise any egos. I respect what you've done knowing full well it was probably done in somebody's free time and as "a labor of love" if you will.

As far as providing clear and fully descriptive examples I did what I thought was needed and apparently, seeing as I got what i needed in the end, I was successful. I trusted if i wasn't clear enough I could describe myself further in follow up comments. Again, I'm far from a super user and more like a layman and, again, I respect what you do but trust me you have to respect others for their lack of knowledge and not assume they are trying to disrespect you.

EDIT: I do apologize, I dont believe I ever thanked you and sorry for any unintended disrespect.

**Comment by fsparv** [comment]
Here's where my natrual helpfulness probably gets me in trouble, but I suppose I'll take your assertion that you don't understand what you did wrong at face value. If you don't see the problems, here's some hints:

> I cant find the .jar file and dont know what your talking about when you ask to change the binary file name to the one supplied. when i try to enter in the supplied command into my command line after changing to the proper directory it only tells me that the associated jar file cannot be run.

Lack of specificity: "enter the supplied command" doesn't tell me which command you are referring to and exactly what you typed. Later you mention windows, but I have to piece that together, and then go look at my front page to see what the command actually is before I can think about what you might have got wrong...  Common problems include typo's so a cut and paste of you exact command is much more helpful, in addition to some indication of where your compiled Leelaz binary is in relation to the command being run... for example I would have been on the lookout for you having omitted the '.'  signifying the current directory that is used in the windows example, but could easily be overlooked for example. If you want free help, on an open source project or in a forum it's important to make sure that the person helping you doesn't have to do a lot of guess work. Provide them with lots of detail (though if it's more than a screen full you need to also ponder whether or not you are drowning them in irrelevant details too). 

> 
> TL/DR: I need a "for dummies" explanation of how to get this to run properly on windows.
> 

"Need" is a demand. "Need" says you think I owe it to you. If you said "I could really use a 'for dummies version' of this", that would show that you understand that you are making a request, but nobody owes you.  

> also, as a side note; a more user friendly version overall of this program 

Implying my program is not user friendly as if it were the most obvious thing in the world, which is somewhere between a complaint and an insult and the off hand style is an implication that I have no clue that user friendliness is of value, but you suppose you might as well take the time to enlighten me... Also this complaint/denigration of the the software is given without any real effort to say what troubled you or confused you or was hard to use, and aside from the screen saver suggestion below, no hint as to what you think would be more friendly. Next time try something like:

Specifically, I don't understand what you mean by "binary file name", perhaps you could explain that in your instructions? Exact steps from start to finish might be more helpful for less savvy folks like me.

Can you see the difference in tone, and helpfulness?

> may do wonders for getting people to contribute to the Leela Zero project. 

A veiled threat that you and/or others won't help unless I respond, or perhaps an accusation that I'm hurting the leela-zero project's prospects, seemingly an attempt to motivate me via negativity. Just don't do this. Stay positive. Threatening a volunteer never works, they just walk away, and then you have no help at all.

> Perhaps a version that runs as a simple screen saver.

THAT was ok, good even. It's a valid suggestion. Suggestions are helpful. Unfortunately it's not one that's easily implemented, but at least you tried. **Do more of that!**

Style and tone matters a lot. This is not a youtube comment stream. Note that your response contains more veiled criticism... "main java file was missing".... again presenting something as if you think it's the most obvious thing in the world and I'm at fault. Instead say directly, "It might be helpful if you add a link to the releases page. I didn't even know that there was a releases page" That's a friendly suggestion with a clear reason that the suggestion would be valuable. 

And again you are defensive and not accepting of your mistakes when you say "I did what I thought was needed and apparently, seeing as I got what i needed in the end, I was successful" That also implies that you don't really care if you were rude as long as you get what you want. This takes a LOT of the glow away from your apology.

"you have to respect others" And you follow up with an accusation that I don't respect people, essentially saying that all this is my fault not yours. You may have tacked an apology on the end, but as written this was a defense not an apology.

"Again, I'm far from a super user and more like a layman" and you're intent on not ever becoming a super user? You don't want to learn? You want the world to spoon feed you so you don't have to learn? You say this like your ignorance a badge of honor, not a deficiency. It's ok to not know everything of course. There's a vast number of topics for which I am a mere novice, but that's my problem, not the problem of the experts I encounter. Your inexperience is not my problem. 

Here's an analogy... If you appear to be running hard and having trouble keeping up many people will slow down (a little bit) for you and help you out (somewhat), but if you stand there yelling about how you're not in good shape and others are going too fast, only your mother will stop for you. The most of rest of the world will just point and laugh as they pass by. A few folks will stop for a moment and suggest some ways to get in better shape (yes, that's this response btw).

Over all, the general tone in everything you've written other than the final one line appology is one of self centered self interest, with a sense that you think you can can convince the world you are superior, or escape blame by implying or pointing out faults in others, and an expectation that the world should accommodate you.

It is quite a (happy) surprise to me that folks as inexperienced as you have been attracted enough to try training Leela zero, and thus found there way here. I wasn't expecting folks who didn't know much about github to get here. The entire thing is by it's nature fairly technical since it generally requires downloading and compiling leela-zero first. However, such adventures that draw one into learning technology can be wonderfully beneficial for folks so I'll go make a few changes on the front page to accommodate a lower level of expertise. 

I primarily learned DOS on an IBM PC XT so that I could copy away the save file for a game (to a 3.5" floppy disk Thus I got around the fact that the game  deleted the save when you died... many years ago :) ). That and a few other adventures, some luck, and the encouragement of others have lead me to a very happy career in programming. Perhaps you or someone else will benefit similarly from this technical adventure. 

Looking closer, I see you just joined github a day ago, so welcome to a whole new world of potential software adventures, and I primarily write this reply in the hope that your next adventure will go more smoothly. This response is quite off topic and should not be taken as a good example of how to use the issue system here by the way!! In that respect I'm setting a bad example! If there were a way to send you this as a personal message I'd have written this to you in that fashion that but as far as I know Github doesn't provide any direct messaging features.

I hope you'll think on this and if you feel wounded by my reply it, think a while longer before replying, or perhaps don't reply at all unless you have something to contribute to the project. In which case it's probably better not to add to this issue, but start a new issue. Thanks for closing the issue, and I'm glad you got things working.
