### ISSUE TITLE
save game to local error

### ISSUE THREAD

**Issue by l1t1** [fsparv/LeelaWatcher#3]
error message is following.
Game data 28f32483346bf8881e99eebc9fdcf122a334486f5053dfdd3300521e7b98fa70 stored in database
3 game(s) played in 1127 minutes = 22552 seconds/game, last game took 53497 seconds.
Best network hash: 1ac2638de9d4d3f9eef43f2afb6b1b4c090a7c350fde4d2d77e00e39eba6fde0
Required client version: 2 (OK)
Already downloaded network.
Engine has started.
Infinite thinking time set.Couldn't save game:java.io.IOException: Incorrect filename, directory name, or volume。

1 (L9)
New Game Started!

        Move:L9

**Comment by FlorinAndrei** [comment]
I got the same error.

Using LeelaWatcher-1.0, Leela Zero 0.6 + AutoGTP v4, Java-1.8.0_151, Windows 10. My bat file is:

```
java -jar LeelaWatcher-1.0.jar . autogtp.exe
```

**Comment by FelixBrendel** [comment]
If you want your sgfs saved you can use `autogtp` capabilities for that.
I have two files in leela zeros folder: `run.bat`
```bat
@echo off
autogtp -k kifu
```
and `runGUI.bat`
```bat
start javaw -jar LeelaWatcher-1.0.jar . run.bat
```
Then just run the `runGUI.bat` file to have your sgfs saved.
By default there will be no console window anymore because of `javaw` if you want the console back just replace it with `java`.

**Comment by l1t1** [comment]
it works, thank you

**Comment by fsparv** [comment]
Felix provided a good workaround, but my program should not give this error :). Going to leave this open
