### ISSUE TITLE
Cleanup MarkablePosition and add tests

### ISSUE THREAD

**Issue by barrybecker4** [fsparv/LeelaWatcher#30]
There are a few things about the MarkablePosition class that I think can be improved. Some are very minor.
 - I don't think there should be blank lines between methods and their javadoc
 - It's unclear to me why the private marks variable needs a leading _
 - There is some code duplication in the getGroupSet method that could be avoided.
 - Why does class javadoc have @version $Revision$? It seems like git already has all the info you need about the version of a file.
 - Why are there revision logs at the bottom? I think they should be removed. Git takes care of history.
 - Can we remove the @SuppressWarnings("unused") annotation. It is used, and there is no warning when I remove it.
 - It would be nice to have unit tests for this class.

I'll make the changes in a PR and you can decide if you want to merge them.

**Comment by fsparv** [comment]
lol, Lots of oldies there...

The _ prefix is something that I briefly picked up from somewhere on the net early on but later came to dispise. A good IDE or failing that this. is sufficient to make fields easily distinguished.

The $Revision$ bit is because this code was written in 2001 and originally under CVS... CVS was far less convenient than git and such things were more common back then.. CVS would perform replacements on things like that see http://web.mit.edu/gnu/doc/html/cvs_17.html

Same with the revision logs... CVS legacy...

Obsolete annotations certainly can be removed. 

In 2001 I had no idea what a unit test was... but yes there's lots of stuff that could be unit tested

**Comment by fsparv** [comment]
Thanks for the patch Barry :)
