### ISSUE TITLE
Go board logic bug

### ISSUE THREAD

**Issue by FelixBrendel** [fsparv/LeelaWatcher#4]
The UI suddenly stopped but the game kept going, later comparing the sgf with the stuck game I found out that something along the way had gone wrong because the game was never in a state the UI suggested. I attached them so you can debug what went wrong.

[bugged replay and scrrenshot.zip](https://github.com/fsparv/LeelaWatcher/files/1500235/bugged.replay.and.scrrenshot.zip)

**Comment by fsparv** [comment]
I've noticed a stopped UI too. Unfortunately there doesn't (yet) seem to be a an error message associated with this. And replaying the attached game, it seems clear that there was a non-fatal initial error, after which play continued for a while before there was probably an attempt to play on top of another stone, because the position in the image never occurs in the game. My initial suspicion is that there was an incomplete capture.

**Comment by fsparv** [comment]
A pull request was made with a suggested fix for this (Thanks :) !), but the problem may go deeper... https://github.com/fsparv/LeelaWatcher/pull/5

**Comment by nsoft** [comment]
The game reported in #9 seems to present a position that falls victim to the problems being discussed in pull request #5
